### ISSUE TITLE
Create a more responsive layout

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#11]
Creating this to supplement a PR already in the works. #9

**Comment by Grill3dCheese** [comment]
Hey @MStewGT - Not sure if you, or someone else, might already be working on this one. However, I was able to implement a new layout using CSS Grid vs. the current Flexbox! 😃 Let me know if you are interested in using this layout - I also tested on all screen sizes and mobile and it appears to be working on all.

Current layout at 1920x1200:
<img width="2032" alt="Screen Shot 2020-10-21 at 6 50 13 PM" src="https://user-images.githubusercontent.com/25601250/96801990-82962200-13ce-11eb-81e4-f52b4aacd824.png">

My solution at 1920x1200:
<img width="2032" alt="Screen Shot 2020-10-21 at 6 50 27 PM" src="https://user-images.githubusercontent.com/25601250/96802016-917cd480-13ce-11eb-886a-dabe0a063a30.png">

**Comment by MStewGT** [comment]
@Grill3dCheese We had merged some changes to the cards previously that also included some layout modifications where we introduced the issue with 4+ columns. This looks good, feel free to open a PR for this so we can take it for a spin.

**Comment by Grill3dCheese** [comment]
Awesome, will do!

**Comment by MStewGT** [comment]
Done! ✔️
