### ISSUE TITLE
Add link to repository

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#17]
Let's add a GitHub logo with a link to the repository. Maybe this could be off to one side in the header.

**Comment by hyunjiLeeTech** [comment]
Hi, I would like to ask this to clarify what you want to. Do you want to add a GitHub logo with a link on the header of your website? If this is what you want to, I would like to take this issue.

**Comment by MStewGT** [comment]
@hyunjiLeeTech Yes that is correct, thanks.
