### ISSUE TITLE
Automatically transform user input

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#2]
Need to take the user’s input and replace any white space in the City name with an underscore (_) to support the API input structure.

**Comment by shahidshakil** [comment]
Can you please assign this to me

**Comment by thomaskvael** [comment]
I have created my first pr for this issue.

**Comment by shashwatbangar** [comment]
hey, @MStewGT it will be my pleasure to work on this project. Can you please assign this to me?

**Comment by MStewGT** [comment]
Assigned this to Thomas since he has something ready.

**Comment by MStewGT** [comment]
Thanks @thomaskvael for you help. Closing this issue as this is verified working now.
