### ISSUE TITLE
Change Brewery display if it is marked as closed

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#22]
It is possible for a Brewery to have a `brewery_type` of "closed". We should visually represent this by turning the card red and displaying the text "Permanently Closed" somewhere on the card. Example: when searching for Kennesaw, we should display Southern Sky Brewing Co as closed.

**Comment by alireza-farokhi** [comment]
Hey @MStewGT , i'm new to contributing, so bare to me pleas ;), i'm up to do this one if you mind
