### ISSUE TITLE
Searching Returns no Breweries - Null Length

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#24]
When searching for a city there is an error and no breweries are returned, blank page. The offending error appears to be "TypeError: Cannot read property 'length' of null" occurring at line 98 in App.js. It appears that a change was made to the API data to mark missing fields as _null_ versus populating with an empty string. 
![image](https://user-images.githubusercontent.com/19848610/124536229-39abbf80-dddd-11eb-846c-0f24d7969f68.png)

**Comment by tristonwyatt** [comment]
I got this :)

**Comment by MStewGT** [comment]
Fix verified and merged! Thanks @tristonwyatt for the contribution.
