### ISSUE TITLE
Turn website link into a button

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#27]
The website link used to have a hover animation but it appears to be broken now. I think it will look cleaner if we just make the website link an actual button.

**Comment by abhikrishnaram** [comment]
@MStewGT could you explain a bit more pls

**Comment by MStewGT** [comment]
> @MStewGT could you explain a bit more pls

Sure, at the bottom of each brewery card there will be a hyperlink to their website if one is returned by the API. I would like to change that hyperlink into a button component. An outlined button would probably work best.

![image](https://user-images.githubusercontent.com/19848610/135725729-2cae0283-5fa5-4bec-9820-0e39ea9ce00a.png)

**Comment by abhikrishnaram** [comment]
@MStewGT i will do it
