### ISSUE TITLE
Fix text spacing within brewery cards

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#3]
The margins around the text in the cards is not even all the way around. Need to make adjustments so that the margins are roughly the same on the top and bottom of the cards.

**Comment by shahidshakil** [comment]
Can you please assign it to me, I am a first time OS contributor.

**Comment by shashwatbangar** [comment]
hey, @MStewGT it will be my pleasure to work on this project. Can you please assign this to me?

**Comment by MStewGT** [comment]
@shahidshakil This one is yours.

@shashwatbangar I opened another Issue for an error message not getting properly presented if you would like to take that one. #6

**Comment by shahidshakil** [comment]
@MStewGT Thanks!, I am on it.
