### ISSUE TITLE
Set a maximum width for brewery cards

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#31]
Brewery cards look ok at 5 or 6 per row but get stretched out if there are only a few returned. I think we should be able to add a maximum width to the cards so that even if only a couple are returned they don't stretch across the entire screen.
![image](https://user-images.githubusercontent.com/19848610/135741499-864a659a-acaa-47d5-a818-75d54f8d871b.png)
![image](https://user-images.githubusercontent.com/19848610/135741514-5c62dae3-6858-49b8-9cbe-05dc0b450d67.png)

**Comment by Gaston82** [comment]
Hello i would like to work on this issue please.
