### ISSUE TITLE
Fix an issue with not presenting an error message when nothing is returned from the API

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#6]
Need to correct an issue with the error message not displaying when there is nothing returned from the API for the user's entered city. This is in the App.js file.
```javascript
if (brewData == null) return ( "Sorry we could not find any results for that location." );
```

**Comment by momosetti** [comment]
You would like to display the error message via toast ?

**Comment by MStewGT** [comment]
> You would like to display the error message via toast ?

@momosetti I was originally just going to show it as plain text on the page below the input field. However, if you think it would work well as a toast notification feel free to give it a go.

**Comment by lnfnunes** [comment]
@MStewGT 
As this issue was idle for a while, I took the initiative to [open a PR](https://github.com/MStewGT/FindMeBeer/pull/9) for this issue.

Glad you like it.
