### ISSUE TITLE
Clear input box on selection

### ISSUE THREAD

**Issue by MStewGT** [MStewGT/FindMeBeer#7]
I think it would be helpful to clear the contents of the input box when selected/clicked to improve the experience of subsequent searches.

**Comment by loiscodes** [comment]
I can take this one

**Comment by loiscodes** [comment]
Just made a PR request: https://github.com/MStewGT/FindMeBeer/pull/8

**Comment by MStewGT** [comment]
This feature is now live! Thanks @loiscodes for the contribution!
